version: '3.4'

services:
  catalogdb:
    image: mongo

  panierdb:
    image: redis:alpine

  promotiondb:
    image: postgres

  commandedb:
    image:  mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image:  rabbitmq:3.9.22-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  panier.api:
    image: ${DOCKER_REGISTRY-}panier
    build:
      context: .
      dockerfile: Services/Panier.Api/Dockerfile

  promotion.api:
    image: ${DOCKER_REGISTRY-}promotion
    build:
      context: .
      dockerfile: Services/Promotion.API/Dockerfile

  promotion.grpc:
    image: ${DOCKER_REGISTRY-}promotiongrpc
    build:
      context: .
      dockerfile: Services/Promotion/Promotion.Grpc/Dockerfile

  commande.api:
    image: ${DOCKER_REGISTRY-}commande
    build:
      context: .
      dockerfile: Services/Commande/Commande.Api/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:




