version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  panierdb:
    container_name: panierdb
    restart: always
    ports:
      - "6379:6379"

  promotiondb:
    container_name: promotiondb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Promotiondb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  commandedb:
    container_name: commandedb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=IneaT123456789
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin1234
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ineat.ca
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "443:443"
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8080:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"


  panier.api:
    container_name: panier.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=panierdb:6379"
      - "GrpcSettings:DiscountUrl=http://promotion.grpc"
      - "ApiSettings:PromotionUrl=http://promotion.api"
      - "EventBusSettings:HostAddress=amqp://admin:admin1234@rabbitmq:5672"
    depends_on:
      - panierdb
      - rabbitmq
    ports:
      - "8001:80"


  promotion.api:
    container_name: promotion.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=promotiondb;Port=5432;Database=Promotiondb;User Id=admin;Password=admin1234;"
    depends_on:
      - promotiondb
    ports:
      - "8002:80"


  promotion.grpc:
    container_name: promotion.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=promotiondb;Port=5432;Database=Promotiondb;User Id=admin;Password=admin1234;"
    depends_on:
      - promotiondb
    ports:
      - "8003:80"


  commande.api:
    container_name: commande.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=commandedb;Database=commandedb;User Id=sa;Password=IneaT123456789;"
      - "EventBusSettings:HostAddress=amqp://admin:admin1234@rabbitmq:5672"
    depends_on:
      - commandedb
      - rabbitmq
    ports:
      - "8004:80"


  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - panier.api
      - promotion.api
      - commande.api
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalog.api"
      - "ApiSettings:PanierUrl=http://panier.api"
      - "ApiSettings:CommandeUrl=http://commande.api"
    depends_on:
      - catalog.api
      - panier.api
      - promotion.api
      - commande.api
    ports:
      - "8005:80"

