version: '3.4'

services:
  catalogdb:
    image: mongo

  panierdb:
    image: redis:alpine

  promotiondb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  panier.api:
    image: ${DOCKER_REGISTRY-}panier
    build:
      context: .
      dockerfile: Services/Panier.Api/Dockerfile

  promotion.api:
    image: ${DOCKER_REGISTRY-}promotion
    build:
      context: .
      dockerfile: Services/Promotion.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

